title: "ereynrs blog"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - ./_posts
  author:
  name             : "ereynrs"
  avatar           : 
  bio              : 
  location         : "Barcelona, Spain"
  employer         :
  pubmed           : 
  googlescholar    : 
  email            : 
  researchgate     : 
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : 
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : 
  lastfm           :
  linkedin         : 
  orcid            : 
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : "ereynrs"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
